// ZKEY constants
module.exports ={
    ZKEY_PF_NSECTIONS: 12,
    
    ZKEY_PF_HEADER_SECTION: 2,
    ZKEY_PF_F_SECTION: 3,
    ZKEY_PF_F_COMMITMENTS_SECTION: 4,
    ZKEY_PF_POLSNAMESSTAGE_SECTION: 5,
    ZKEY_PF_CONST_POLS_EVALS_SECTION: 6,
    ZKEY_PF_CONST_POLS_COEFS_SECTION: 7,
    ZKEY_PF_CONST_POLS_EVALS_EXT_SECTION: 8,
    ZKEY_PF_X_N_SECTION: 9,
    ZKEY_PF_X_EXT_SECTION: 10,
    ZKEY_PF_OMEGAS_SECTION: 11,
    ZKEY_PF_PTAU_SECTION: 12,
}
