// ZKEY constants
module.exports ={
    ZKEY_PF_NSECTIONS: 6,
    
    ZKEY_PF_HEADER_SECTION: 2,
    ZKEY_PF_F_SECTION: 3,
    ZKEY_PF_F_COMMITMENTS_SECTION: 4,
    ZKEY_PF_POLSMAP_SECTION: 5,
    ZKEY_PF_OMEGAS_SECTION: 6
}
